RANDOM_SEED: 23567
MODEL:
  TYPE: "maskdino"
  CONFIG: ./configs/maskdino/maskdino_R50_bs16_160k_steplr.yaml
  WEIGHTS: ./checkpoints/maskdino/maskdino_r50_50ep_100q_celoss_hid1024_3s_semantic_ade20k_48.7miou.pth
  NUM_CLASSES: 150
DATASET:
  TEST:
    TYPE: "multistep"
    MODE: "test"
    ANNOTATION_ROOT: "data/segmatron_habitat/annotations/segmatron_v1_val.json"
    IMAGE_ROOT: "data/segmatron_habitat/val"
EVALUATOR:
  TYPE: "random_policy_evaluator"
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  OUTPUT_DIRECTORY: "evaluation_results/maskdino_single_frame_habitat"
  CHECKPOINT: "checkpoints/maskdino_single_frame.pt"